### ISSUE TITLE
High-Fidelity Prototype of UBD application

### ISSUE THREAD

**Issue by AziziAlmina** [ariftairi/Agile-Software-Development#12]
The Urgent Blood Donation application's high-fidelity prototype is designed using the technology called Proto.io.

**Comment by zanasalii** [comment]
[Proto.io](https://pr.to/MN58U2/) 
The prototype is designed for iPhone 8 (375 x 667) and to be the testing of prototype efficient you can use that type of mobile device. As the goal of the prototype is to prove that what was designed is possible, we aimed to show that all the drawings will make something useful. We wanted to stimulate the interaction between the user and interface as realistically as possible. For example, when a button is clicked, the specific operation must be carried out and then the corresponding pages must appear. So, to give an answer to the question “what will happen if I click the button?”, we design the prototype to make that button functional and by clicking on it, let the users see how it works and what it does. The other purpose of this prototype is testing the satisfaction of the users which will help us see how the users feel about the product before releasing it to market. Using prototyping, makes us sure that the product is made according to users need and any modification can be done before the development of the final product. Moreover, we build a vertical prototype, since are more technically in nature and are useful in demonstrating that a set of requirements are technically feasible.

**Comment by zanasalii** [comment]
Professor ,if you want to open the link (Proto.io) , please try it from your phone because it only opens there . Thank you.
